### PR TITLE
enable cpuid on arm64, pcc64el, and other architectures

### PR DESCRIPTION
**Pull request by mr-c**
By synchronizing with upstream parasail

https://github.com/jeffdaily/parasail/blob/600fb26151ff19899ee39a214972dcf2b9b11ed7/src/cpuid.c

### CODE REVIEW

**Comment by brianwalenz** [comment]
Woot!  Thanks a lot!

**Comment by mr-c** [comment]
> Woot! Thanks a lot!

Thanks! FYI, those install from source will still need to set `-DHAVE_ALTIVEC=-1` or `-DHAVE_NEON=1` on POWER8+ systems & arm64 systems (respectively)

**Comment by brianwalenz** [comment]
What do
```
uname
uname -r
uname -m
```
return on your systems?  I'll attempt to get those set automatically, but I can only test on a Mac Mini.

If you wan to take a shot at it, the `uname` queries are at line 45 in Makefile.boilermake, and machine-specific flags can be added at line 129 in Makefile.  There's also compiler detection via variable TOOLCHAIN.

**Comment by mr-c** [comment]
> What do
> 
> ```
> uname
> uname -r
> uname -m
> ```
> 
> return on your systems? I'll attempt to get those set automatically, but I can only test on a Mac Mini.
> 
> If you wan to take a shot at it, the `uname` queries are at line 45 in Makefile.boilermake, and machine-specific flags can be added at line 129 in Makefile. There's also compiler detection via variable TOOLCHAIN.

See https://wiki.debian.org/ArchitectureSpecificsMemo . The main Debian architectures are amd64 i386 arm64 armhf armel mips64el ppc64el riscv64 s390x

**Comment by brianwalenz** [comment]
Thanks!  I was working on Makefile support for this yesterday, but got sidetracked into different MacOS problem.

**Pull request merged**
